[package]
name = "synth-node"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = { version = "0.13", default-features = false }
dasp_graph = { version = "0.11", default-features = false, features = [ "all-nodes" ] }
rtrb = "0.2"
