[package]
name = "synth"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
cpal = "0.13"
dasp_graph = { version = "0.11", features = [ "all-nodes" ] }
petgraph = { version = "0.5", default-features = false }
rtrb = "0.2"
