[package]
name = "synth-module-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
petgraph = { version = "0.5", default-features = false }
proc-macro-error = { version = "1.0", features = [ "syn-error" ] }
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"
